# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ECMxp232uHVmG7wF56hMsMVbJ2MYbQ7
"""



import streamlit as st
from groq import Groq
api_key = "gsk_XXXXXXXX"
llm = Groq(api_key=api_key)
messages = [
    {"role": "system", "content": "i am a helpful assistant"},
]
def run_llm(prompt):
    messages.append({"role": "user", "content": prompt})

    LLM = llm.chat.completions.create(
        model="qwen/qwen3-32b",  # نفس الموديل
        messages=messages,
        max_tokens=100000,
        temperature=0.3
    )

    reply = LLM.choices[0].message.content
    messages.append({"role": "assistant", "content": reply})
    return reply

"""**Streamlit UI**


"""

st.title('My llm app')
st.header('ask the assistant:')
st.write('welcome to my first llm app!')
user_input=st.text_input('enter your question here:')
if st.button('Try to click me to get the answer!'):
  if user_input.strip() !="":
    reply=run_llm(user_input)
    st.success(reply)
  else:
    st.warning('please enter your question!')
